### ISSUE TITLE
Push TypeError

### ISSUE THREAD

**Issue by RenFinkle** [neocities/neocities-ruby#22]
I'm encountering some odd behavior on my second try pushing to neocities (neocities client version 0.0.13 on Ubuntu 18.04.2 LTS), the first try worked fine but now I'm getting this error:
```
Traceback (most recent call last):
        9: from /usr/local/bin/neocities:23:in `<main>'
        8: from /usr/local/bin/neocities:23:in `load'
        7: from /var/lib/gems/2.5.0/gems/neocities-0.0.13/bin/neocities:4:in `<top (required)>'
        6: from /var/lib/gems/2.5.0/gems/neocities-0.0.13/lib/neocities/cli.rb:79:in `run'
        5: from /var/lib/gems/2.5.0/gems/neocities-0.0.13/lib/neocities/cli.rb:185:in `push'
        4: from /var/lib/gems/2.5.0/gems/neocities-0.0.13/lib/neocities/cli.rb:185:in `chdir'
        3: from /var/lib/gems/2.5.0/gems/neocities-0.0.13/lib/neocities/cli.rb:190:in `block in push'
        2: from /var/lib/gems/2.5.0/gems/neocities-0.0.13/lib/neocities/cli.rb:190:in `collect!'
        1: from /var/lib/gems/2.5.0/gems/neocities-0.0.13/lib/neocities/cli.rb:191:in `block (2 levels) in push'
/var/lib/gems/2.5.0/gems/neocities-0.0.13/lib/neocities/cli.rb:191:in `directory?': no implicit conversion of nil into String (TypeError)
```
If there is any other info I could provide to help diagnose this behavior please let me know!

**Comment by RenFinkle** [comment]
Resolved by putting a newline at the end of the gitignore.
