### ISSUE TITLE
Expiring On Push

### ISSUE THREAD

**Issue by RenFinkle** [neocities/neocities-ruby#26]
When I try to push to my site, after entering my login credentials, I get this error message:
```
Traceback (most recent call last):
        20: from /usr/local/bin/neocities:23:in `<main>'
        19: from /usr/local/bin/neocities:23:in `load'
        18: from /var/lib/gems/2.5.0/gems/neocities-0.0.13/bin/neocities:4:in `<top (required)>'
        17: from /var/lib/gems/2.5.0/gems/neocities-0.0.13/lib/neocities/cli.rb:66:in `run'
        16: from /var/lib/gems/2.5.0/gems/neocities-0.0.13/lib/neocities/client.rb:38:in `key'
        15: from /var/lib/gems/2.5.0/gems/neocities-0.0.13/lib/neocities/client.rb:76:in `get'
        14: from /var/lib/gems/2.5.0/gems/httpclient-2.8.3/lib/httpclient.rb:743:in `get'
        13: from /var/lib/gems/2.5.0/gems/httpclient-2.8.3/lib/httpclient.rb:856:in `request'
        12: from /var/lib/gems/2.5.0/gems/httpclient-2.8.3/lib/httpclient.rb:1014:in `do_request'
        11: from /var/lib/gems/2.5.0/gems/httpclient-2.8.3/lib/httpclient.rb:1133:in `protect_keep_alive_disconnected'
        10: from /var/lib/gems/2.5.0/gems/httpclient-2.8.3/lib/httpclient.rb:1019:in `block in do_request'
         9: from /var/lib/gems/2.5.0/gems/httpclient-2.8.3/lib/httpclient.rb:1242:in `do_get_block'
         8: from /var/lib/gems/2.5.0/gems/httpclient-2.8.3/lib/httpclient/session.rb:177:in `query'
         7: from /var/lib/gems/2.5.0/gems/httpclient-2.8.3/lib/httpclient/session.rb:511:in `query'
         6: from /var/lib/gems/2.5.0/gems/httpclient-2.8.3/lib/httpclient/session.rb:748:in `connect'
         5: from /usr/lib/ruby/2.5.0/timeout.rb:103:in `timeout'
         4: from /var/lib/gems/2.5.0/gems/httpclient-2.8.3/lib/httpclient/session.rb:752:in `block in connect'
         3: from /var/lib/gems/2.5.0/gems/httpclient-2.8.3/lib/httpclient/ssl_socket.rb:21:in `create_socket'
         2: from /var/lib/gems/2.5.0/gems/httpclient-2.8.3/lib/httpclient/session.rb:611:in `create_socket'
         1: from /var/lib/gems/2.5.0/gems/httpclient-2.8.3/lib/httpclient/session.rb:611:in `new'
/var/lib/gems/2.5.0/gems/httpclient-2.8.3/lib/httpclient/session.rb:611:in `initialize': execution expired (HTTPClient::ConnectTimeoutError)
```

**Comment by da2x** [comment]
Does this still happen or was it a temporary issue?

**Comment by 11808s8** [comment]
Hey @da2x , 
this exact same issue was occurring for me with the neocities cli since I've started using it. I'm running it on top of a Ubuntu 18.04.4 LTS (output courtesy of a `hostnamectl`. I can post the kernel ver if needed).  

After digging around a bit, this error seems to span far out of the cli scope and adding `require 'resolv-replace'` to the top of the neocities cli.rb file completely solved it for me, a solution found on [1]. Please find the output of the error on [2] (although it is the same as @RenFinkle posted).
 
Are there any specific guidelines for contributing to the neocities cli repo/code itself? My only experience around Ruby is with Chef, so I'm not familiar if doing this "require" on that specfic file would be best practices as well.

Cheers!


[1] https://stackoverflow.com/a/42043142
[2] 
```
$ sudo neocities push --dry-run .
Doing a dry run, not actually pushing anything
Uploading assets/backgrounds/worldly.webp ... Traceback (most recent call last):
        26: from /usr/local/bin/neocities:23:in `<main>'
        25: from /usr/local/bin/neocities:23:in `load'
        24: from /var/lib/gems/2.5.0/gems/neocities-0.0.15/bin/neocities:4:in `<top (required)>'
        23: from /var/lib/gems/2.5.0/gems/neocities-0.0.15/lib/neocities/cli.rb:79:in `run'
        22: from /var/lib/gems/2.5.0/gems/neocities-0.0.15/lib/neocities/cli.rb:191:in `push'
        21: from /var/lib/gems/2.5.0/gems/neocities-0.0.15/lib/neocities/cli.rb:191:in `chdir'
        20: from /var/lib/gems/2.5.0/gems/neocities-0.0.15/lib/neocities/cli.rb:222:in `block in push'
        19: from /var/lib/gems/2.5.0/gems/neocities-0.0.15/lib/neocities/cli.rb:222:in `each'
        18: from /var/lib/gems/2.5.0/gems/neocities-0.0.15/lib/neocities/cli.rb:225:in `block (2 levels) in push'
        17: from /var/lib/gems/2.5.0/gems/neocities-0.0.15/lib/neocities/client.rb:54:in `upload'
        16: from /var/lib/gems/2.5.0/gems/neocities-0.0.15/lib/neocities/client.rb:42:in `upload_hash'
        15: from /var/lib/gems/2.5.0/gems/neocities-0.0.15/lib/neocities/client.rb:86:in `post'
        14: from /var/lib/gems/2.5.0/gems/httpclient-2.8.3/lib/httpclient.rb:765:in `post'
        13: from /var/lib/gems/2.5.0/gems/httpclient-2.8.3/lib/httpclient.rb:856:in `request'
        12: from /var/lib/gems/2.5.0/gems/httpclient-2.8.3/lib/httpclient.rb:1014:in `do_request'
        11: from /var/lib/gems/2.5.0/gems/httpclient-2.8.3/lib/httpclient.rb:1133:in `protect_keep_alive_disconnected'
        10: from /var/lib/gems/2.5.0/gems/httpclient-2.8.3/lib/httpclient.rb:1019:in `block in do_request'
         9: from /var/lib/gems/2.5.0/gems/httpclient-2.8.3/lib/httpclient.rb:1242:in `do_get_block'
         8: from /var/lib/gems/2.5.0/gems/httpclient-2.8.3/lib/httpclient/session.rb:177:in `query'
         7: from /var/lib/gems/2.5.0/gems/httpclient-2.8.3/lib/httpclient/session.rb:511:in `query'
         6: from /var/lib/gems/2.5.0/gems/httpclient-2.8.3/lib/httpclient/session.rb:748:in `connect'
         5: from /usr/lib/ruby/2.5.0/timeout.rb:103:in `timeout'
         4: from /var/lib/gems/2.5.0/gems/httpclient-2.8.3/lib/httpclient/session.rb:752:in `block in connect'
         3: from /var/lib/gems/2.5.0/gems/httpclient-2.8.3/lib/httpclient/ssl_socket.rb:21:in `create_socket'
         2: from /var/lib/gems/2.5.0/gems/httpclient-2.8.3/lib/httpclient/session.rb:611:in `create_socket'
         1: from /var/lib/gems/2.5.0/gems/httpclient-2.8.3/lib/httpclient/session.rb:611:in `new'
/var/lib/gems/2.5.0/gems/httpclient-2.8.3/lib/httpclient/session.rb:611:in `initialize': execution expired (HTTPClient::ConnectTimeoutError)
```
